branch-defaults:
  master:
    environment: ENV-ows-myproduct
global:
  application_name: ows-myproduct
  default_ec2_keyname: orchard_admin
  default_platform: null
  default_region: null
  profile: null
  sc: git
deploy:
  artifact: ows-myproduct.zip
